const TMDB_API_KEY = process.env.REACT_APP_TMDB_API_KEY;
const TMDB_BASE_URL = process.env.REACT_APP_TMDB_BASE_URL;
const TMDB_EMBED_MOVIE_URL = process.env.REACT_APP_EMBED_MOVIE_URL;
const TMDB_EMBED_SERIES_URL = process.env.REACT_APP_EMBED_SERIES_URL;
const TMDB_IMAGE_URL = process.env.REACT_APP_TMDB_IMG_URL;

module.exports = {
  TMDB_API_KEY: TMDB_API_KEY,
  TMDB_BASE_URL: TMDB_BASE_URL,
  TMDB_EMBED_MOVIE_URL: TMDB_EMBED_MOVIE_URL,
  TMDB_EMBED_SERIES_URL: TMDB_EMBED_SERIES_URL,
  TMDB_IMAGE_URL: TMDB_IMAGE_URL,
};
